### ISSUE TITLE
User Model forceDelete doesn't remove the record from the DB

### ISSUE THREAD

**Issue by lcharette** [userfrosting/UserFrosting#951]
When using the User model `forceDelete` option (`$user->delete(true)`), the record is still soft deleted, not removed from the db. The `delete` method doesn't seam to return true as supposed to. Possible user facing error too : https://chat.userfrosting.com/channel/support?msg=QbMRJX7uhHHahFLZi

**Comment by claudious96** [comment]
My setup:
- Apache 2.4.37 
- MariaDB 10.1.37 (tested also with MySql 5.7.25)
- PHP 7.3.0 (tested also with 7.2.15)

This error shows up in the modal when trying to force delete a user 
![immagine](https://user-images.githubusercontent.com/32904044/55318503-3b0a1700-5473-11e9-9ab6-4ad41ef53ddd.png)

In the browser console doesn't come up anything,  the response to the `DELETE`  request is just a `status code 500`.

Commenting [#L192](https://github.com/userfrosting/UserFrosting/blob/master/app/sprinkles/account/src/Database/Models/User.php#L192) in the User model the error disappears but it still performs SoftDelete.

I also checked in UF 4.1 and the bug is also there (no error shows up), so it shouldn't be caused by the foreign key added in UF 4.2 .

**Comment by lcharette** [comment]
This bug is successfully replicated on the `hotfix-userIssue` branch [with a new test](https://github.com/userfrosting/UserFrosting/blob/hotfix-userIssue/app/sprinkles/account/tests/Unit/UserModelTest.php#L59-L68). However, apparently this is a bug in Eloquent itself, which was fixed with Laravel version 5.5: https://github.com/laravel/framework/pull/9806#issuecomment-276717616

We're still on 5.4, which explain why we're still seeing this. There is not much we can do for now I guess. I'll leave this issue open and mark it for UF 4.3 so we can confirm it is indeed fixed when we update our Laravel dependency.

**Comment by claudious96** [comment]
That issue is not exactly the same bug, it is still a problem but the bug here is being unable to perform hard deletes even without having already soft-deleted the user.

I started digging a little bit more into this problem and I think there are three possible causes, the last 2 are about the error I got:
- the first one (I'm quite sure about this one) is [User.php#L201](https://github.com/userfrosting/UserFrosting/blob/master/app/sprinkles/account/src/Database/Models/User.php#L201) (and as a consequence also ([User.php#L204](https://github.com/userfrosting/UserFrosting/blob/master/app/sprinkles/account/src/Database/Models/User.php#L204)) ). Using `parent::` the call falls back to the method defined in the class that is extended (`Model`), to use the method defined in the `SoftDeletes` trait, should be instead `$this->forceDelete();` and `$this->delete();`. Just for clarity's sake here is a [snippet code](https://pastebin.com/dNv1sjZv) to clarify this. 
- the second one could be the need to delete any persistences related to the user since each row is referenced to a `user_id`.
- the third I think (I'm not sure about this), could be the ['circular foreign keys'](https://dba.stackexchange.com/questions/102903/is-it-acceptable-to-have-circular-foreign-key-references-how-to-avoid-them) between the `users` table and the `activities` table. In fact each user's last activity column must be referenced to an activity's `id` and also each activity's `user_id` must be referenced to an actual user's id. This means that none of the two (or more) instances can be deleted before the other one. This explains why I could avoid the alert in the modal, commenting [#L192](https://github.com/userfrosting/UserFrosting/blob/master/app/sprinkles/account/src/Database/Models/User.php#L192).

The first I think could be easily fixed with the edits I wrote above (although there is the possibility of unpredictable behaviour of the code like in the snippet).
The second could be solved just adding a new class mapping in the ServicesProvider and then deleting just like done with the other instances.
About the third, I cannot see a solution that would not involve a new migration. For the future could be also considered to add `onDelete('cascade')` when defining the foreign keys (see [this question in SO](https://stackoverflow.com/questions/26820788/add-on-delete-cascade-to-existing-column-in-laravel) ).

I'm not an expert PHP coder so I'm likely missing something. I'd love some kind of feedback, if needed I could also work on a PR.

**Comment by lcharette** [comment]
Actually, you're right. I got distracted by another test I did. 

Your first point was right on target. `$result = parent::forceDelete();` in [User.php#L201](https://github.com/userfrosting/UserFrosting/blob/master/app/sprinkles/account/src/Database/Models/User.php#L201) should be `$result = $this->forceDelete();`. No need to use `parent::` in that situation, as it should only be used to refer to the same method in the parent class. 

That's why changing `parent::delete();` into `$this->delete();` didn't worked for you, as you where referencing the same method and creating an infinite loop. 

Should be fixed in commit 3790e4f, I'll merge into `hotfix` branch, if you can confirm it work before we release the fix in 4.2.1

**Comment by claudious96** [comment]
> That's why changing parent::delete(); into $this->delete(); didn't worked for you, as you where referencing the same method and creating an infinite loop.

Yes, it makes perfectly sense.
I tested it and now it works only in case the user is created from the admin panel and then deleted (so no activities logged), otherwise the error brakes the whole delete operations.

Since you could not reproduce the error I got in the modal, I guess it depends on the DB server.
Here is my fix for my setup mentioned above, it is backward compatible it disables the foreign key check until the end of the operation and then enables it again. 
If it doesn't make it to the hotfix it might be useful for somebody someday.
First I defined the classMapping of persistence model inside `ServicesProvider.php`
```
$container->extend('classMapper', function ($classMapper, $c) {
           ...
            $classMapper->setClassMapping('verification', 'UserFrosting\Sprinkle\Account\Database\Models\Verification');

            return $classMapper;
        });
```
And this is how my `delete` method of the `User` model looks like
```
public function delete($hardDelete = false)
    {
        /** @var \UserFrosting\Sprinkle\Core\Util\ClassMapper $classMapper */
        $classMapper = static::$ci->classMapper;

        if ($hardDelete) {
            // Remove all role associations
            $this->roles()->detach();

            static::$ci->db->schema()->disableForeignKeyConstraints();
            // Remove all user activities
            $classMapper->staticMethod('activity', 'where', 'user_id', $this->id)->delete();

            // Remove all user tokens
            $classMapper->staticMethod('password_reset', 'where', 'user_id', $this->id)->delete();
            $classMapper->staticMethod('verification', 'where', 'user_id', $this->id)->delete();
            $classMapper->staticMethod('persistence', 'where', 'user_id', $this->id)->delete();

            // Delete the user
            $result = $this->forceDelete();
            static::$ci->db->schema()->enableForeignKeyConstraints();
        } else {
            // Soft delete the user, leaving all associated records alone
            $result = parent::delete();
        }

        return $result;
    }
```

**Comment by lcharette** [comment]
Hum, you might be right again. Delete might be missing some cleanup. I wonder if we would need to delete roles or other tables. Delete cascade would be easier indeed.

**Comment by claudious96** [comment]
Well, the cleaning of roles works well with `detach()` as far as I can see from the tests I tried today. 
About cleaning the other tables, I based my thoughts on the migrations that adds the foreign keys. I could have missed something but should be fine like this.

**Comment by lcharette** [comment]
Hum, can you open a new issue about this, as this one has already been merged?

Thanks.
